FROM node

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
RUN mkdir -p  /usr/src/app/logs/api
RUN chown -R node:node /usr/src/
RUN chmod -R 777 /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

EXPOSE 4003

CMD ["npm", "run", "dev"]
