###
# 학생 가입
POST http://localhost:3000/join
Content-Type: application/json

{
  "no": "20210010001",
  "password": "asdf1234",
  "info": {
    "name": "홍길동",
    "email": "hong@test.com",
    "phone": "01012341234",
    "department": "소프트웨어학과"
  }
}

###
# 학생 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "no": "20210010001",
  "password": "asdf1234"
}

###
# 내 정보 가져오기(학생)
GET http://localhost:3000/me
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjVlZWE2ZTY1ZTVhYjhiODFiMjEiLCJyb2xlcyI6WyJzdGFmZiJdLCJwZXJtaXNzaW9ucyI6W10sImluZm8iOiI2MDUxNjVlZWE2ZTY1ZTVhYjhiODFiMjIiLCJpYXQiOjE2MTU5NDczNTMsImV4cCI6MTYxNTk0Nzk1MywiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.Wy9XsvIcr4m_rrlwQmxqhvsWgHABHtDWe0pnOS3kwrrcoiuJ_QSmkQN1lbrcMKQXGP3C1erGIEPdEImREXIxwg


###
# Token Validate
GET http://localhost:3000/token/validate
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2MzQxMjY5NTY0NWE2MDA0ZWZjMSIsImlhdCI6MTYxNTk0NjU3MCwiZXhwIjoxNjE1OTQ3MTcwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.VQyTaSGFS3GzOvhm4u7uLuw9K7nEMAsDS8jnSe--zgMRqlGygAjp346uEY4-mDyT-wdUH5XuoUNQCBKqCRInKQ

###
# Refresh token
GET http://localhost:3000/token/refresh
x-refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJpYXQiOjE2MTU5NDcxMTMsImV4cCI6MTYxNzI0MzExMywiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.V-zDc8NkXxCb7qrR-lVhBZkJLcXfBh-01yu67iuREj_28wfPPpSeixIzAa2w2rBKWv-5RYnOPi5ZVYDv7yoWsQ

###
# Logout
GET http://localhost:3000/logout
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2MzQxMjY5NTY0NWE2MDA0ZWZjMSIsImlhdCI6MTYxNTk0NzEzMiwiZXhwIjoxNjE1OTQ3NzMyLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.DtOAEvN2_suTXyys6UJeIQnq3SUJUjHus9pmEf2bQ7gjS7Ids26RdujrOpGHOwUWOlbWNbuYZkH7AG-wTPkqKg
x-refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJpYXQiOjE2MTU5NDcxMzIsImV4cCI6MTYxNzI0MzEzMiwiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.t-Dz1XHZQf84ckCV8Mox61tNqCOGe-EGsFtFyedfNynjWTS-JdUvaBPig2m3AvrF23hcP0snxYValB-uUBi9-Q

###
# 교직원 회원 가입
POST http://localhost:3000/join
Content-Type: application/json

{
  "no": "123121",
  "password": "asdf1234",
  "role": "staff",
  "info": {
    "name": "김교수",
    "email": "kim@cbnu.ac.kr",
    "phone": "01021212121",
    "department": "소프트웨학과",
    "position": "교수"
  }
}

###
# 교직원 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "no": "123121",
  "password": "asdf1234"
}

###
# 운영자 로그인(권한 없는 사람 로그인)
POST http://localhost:3000/operator/login
Content-Type: application/json

{
  "no": "123121",
  "password": "asdf1234"
}

###
# 운영자 로그인
POST http://localhost:3000/operator/login
Content-Type: application/json

{
  "no": "12345",
  "password": "asdf"
}

###
# 내 정보 가져오기(내 정보)
GET http://localhost:3000/me
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjIiLCJyb2xlcyI6WyJvcGVyYXRvciJdLCJwZXJtaXNzaW9ucyI6WyJzdHVkZW50Iiwibm90aWNlIl0sImluZm8iOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjMiLCJpYXQiOjE2MTQ3Mjk2OTEsImV4cCI6MTYxNDczMDI5MSwiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.kNT-hGsX6afxfmBpvubzUsQDV17gM02P3j9cE02Y65d-_Tw1KtPCRKp87mBFCZHLfiYCMq6VpIuC7wmocqBwsw

###
# otp 보내기
POST http://localhost:3000/otp/send
Content-Type: application/json

{
  "name": "관리자",
  "email": "kmahn@cbnu.ac.kr"
}

###
# Check OTP
POST http://localhost:3000/otp/check
Content-Type: application/json

{
  "name": "관리자",
  "email": "kmahn@cbnu.ac.kr",
  "code": "387259"
}

###
# Init Password
POST http://localhost:3000/password/init
Content-Type: application/json

{
  "name": "관리자",
  "email": "kmahn@cbnu.ac.kr",
  "code": "387259",
  "password": "asdf1234"
}

###
# 내 정보 수정
PUT http://localhost:3000/me
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjIiLCJyb2xlcyI6WyJvcGVyYXRvciJdLCJwZXJtaXNzaW9ucyI6WyJzdHVkZW50Iiwibm90aWNlIl0sImluZm8iOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjMiLCJpYXQiOjE2MTQ3MzE1MzEsImV4cCI6MTYxNDczMjEzMSwiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.GEcY3Pm5R52snBFrbp0GtaBkpryEXk10WEepQyu3bmmkR2wBsW4elVmvdCKZlxXdu7AqyyVuHaUvAeIyPcV89w
Content-Type: application/json

{
  "name": "운영자",
  "department": "사업팀"
}

###
# 수정된 내 정보 확인
GET http://localhost:3000/me
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjIiLCJyb2xlcyI6WyJvcGVyYXRvciJdLCJwZXJtaXNzaW9ucyI6WyJzdHVkZW50Iiwibm90aWNlIl0sImluZm8iOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjMiLCJpYXQiOjE2MTQ3MzE1MzEsImV4cCI6MTYxNDczMjEzMSwiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.GEcY3Pm5R52snBFrbp0GtaBkpryEXk10WEepQyu3bmmkR2wBsW4elVmvdCKZlxXdu7AqyyVuHaUvAeIyPcV89w

###
# 내 비밀번호 수정
PATCH http://localhost:3000/password
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjIiLCJyb2xlcyI6WyJvcGVyYXRvciJdLCJwZXJtaXNzaW9ucyI6WyJzdHVkZW50Iiwibm90aWNlIl0sImluZm8iOiI2MDNlY2U2OTYwY2JlODM4MGM3NGMzMjMiLCJpYXQiOjE2MTQ3MzE1MzEsImV4cCI6MTYxNDczMjEzMSwiYXVkIjoiaHR0cHM6Ly9zdzd1cC5jYm51LmFjLmtyIiwiaXNzIjoi7Lap67aB64yA7ZWZ6rWQIFNX7KSR7Ius64yA7ZWZ7IKs7JeF64uoIiwic3ViIjoia21haG5AY2JudS5hYy5rciJ9.GEcY3Pm5R52snBFrbp0GtaBkpryEXk10WEepQyu3bmmkR2wBsW4elVmvdCKZlxXdu7AqyyVuHaUvAeIyPcV89w
Content-Type: application/json

{
  "oldPassword": "asdf",
  "newPassword": "asdf1234"
}

###
# 바뀐 비밀번호로 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "no": "12345",
  "password": "asdf1234"
}
