version: "3.9"

services:
  zookeeper:
    image: zookeeper
    
    expose:
      - "2181"
    
    volumes:
      - ./zookeeper/conf:/conf


  kafka:
    image: wurstmeister/kafka
    
    expose:
      - "9092"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_BROKER_ID: 1
      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      KAFKA_ADVERTISED_HOST_NAME: kafka

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      
      KAFKA_CREATE_TOPICS: "swjudge-submit:4:1,\
                            swjudge-result:4:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      
      KAFKA_HEAP_OPTS: "-Xms8g -Xmx16g"
    
    depends_on:
      - zookeeper


  judger-api:
    build:
      context: ./judger-backend/judger-api
      dockerfile: Dockerfile
    env_file:
      - ./judger-backend/judger-api/.env

    expose:
      - "4003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
      - /uploads:/usr/src/app/uploads
      - /server-Logs:/usr/src/app/logs
    
    depends_on:
      - kafka
    links:
      - kafka


  judger-web:
    build:
      context: ./judger-frontend
      dockerfile: Dockerfile

    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./judger-frontend/nginx/ssl:/etc/nginx/ssl
    
    depends_on:
      - judger-api
    links:
      - judger-api


  judger1:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile
    env_file:
      - ./judger-backend/judger/.env
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
      - /uploads:/source
      - /uploads:/io
    
    depends_on:
      - kafka
    links:
      - kafka


  judger2:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile
    env_file:
      - ./judger-backend/judger/.env
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
      - /uploads:/source
      - /uploads:/io
    
    depends_on:
      - kafka
    links:
      - kafka


  judger3:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile
    env_file:
      - ./judger-backend/judger/.env
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
     
    volumes:
      - /uploads:/source
      - /uploads:/io
  
    depends_on:
      - kafka
    links:
      - kafka


  judger4:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile
    env_file:
      - ./judger-backend/judger/.env
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
      - /uploads:/source
      - /uploads:/io
    
    depends_on:
      - kafka
    links:
      - kafka


  judger5:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile
    env_file:
      - ./judger-backend/judger/.env
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
      - /uploads:/source
      - /uploads:/io
    
    depends_on:
      - kafka
    links:
      - kafka