FROM node

RUN mkdir /usr/src/logs

RUN chown -R node:node /usr/src/logs

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

EXPOSE 4003

CMD ["npm", "run", "dev"]
