import ConditionalNavbar from './components/ConditionalNavbar';
import Footer from './components/Footer';
import Toast from './components/toast/Toast';
import './globals.css';
import Providers from '@/utils/Providers';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: 'Judge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/cube-logo.png" />
      </head>
      <body className="text-sm">
        <Providers>
          <ConditionalNavbar />
          <SpeedInsights />
          <Toast />
          <main className="w-full mx-auto pt-[6rem] mb-[10rem]">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
