FROM node:16.14.0

# Create app directory
RUN mkdir -p /app

WORKDIR /app

# Install dependencies
COPY package*.json /app/
RUN npm install

# Copy the rest of the project files
COPY . /app/

# Expose the Next.js dev server port
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"]

