name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      # 3. judger-frontend 의존성 캐시 복원 및 설치
      - name: Restore npm cache for frontend
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-frontend-${{ hashFiles('judger-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-frontend-

      - name: Install dependencies for frontend
        run: npm ci
        working-directory: ./judger-frontend

      - name: Run lint for frontend
        run: npm run lint
        working-directory: ./judger-frontend

      # 4. judger-backend/judger 의존성 캐시 복원 및 설치
      - name: Restore npm cache for backend judger
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-judger-${{ hashFiles('judger-backend/judger/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-judger-

      - name: Install dependencies for backend judger
        run: npm ci
        working-directory: ./judger-backend/judger

      # 5. judger-backend/judger-api 의존성 캐시 복원 및 설치
      - name: Restore npm cache for backend judger-api
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-judger-api-${{ hashFiles('judger-backend/judger-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-judger-api-

      - name: Install dependencies for backend judger-api
        run: npm ci
        working-directory: ./judger-backend/judger-api
